// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-A9ax7D-nGulklTvT1P2dXhtvrawP21c',
    appId: '1:305904223967:web:43d7d0cde17bef43b38b6a',
    messagingSenderId: '305904223967',
    projectId: 'hotel-management-app-3f47e',
    authDomain: 'hotel-management-app-3f47e.firebaseapp.com',
    storageBucket: 'hotel-management-app-3f47e.appspot.com',
    measurementId: 'G-BH0835G40Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLABRF9SX6pyMotDpAFCNbVpO4uumDfI',
    appId: '1:305904223967:android:2195479cf21d19d8b38b6a',
    messagingSenderId: '305904223967',
    projectId: 'hotel-management-app-3f47e',
    storageBucket: 'hotel-management-app-3f47e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcMTwOOhjgUDcQndBSjYjvCueNJmFO9QY',
    appId: '1:305904223967:ios:103772266c852c29b38b6a',
    messagingSenderId: '305904223967',
    projectId: 'hotel-management-app-3f47e',
    storageBucket: 'hotel-management-app-3f47e.appspot.com',
    iosClientId: '305904223967-1ogbuahklavb9s6edbcepneq24e5e3hm.apps.googleusercontent.com',
    iosBundleId: 'com.showoff.hotelManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcMTwOOhjgUDcQndBSjYjvCueNJmFO9QY',
    appId: '1:305904223967:ios:17f5e7f560187c18b38b6a',
    messagingSenderId: '305904223967',
    projectId: 'hotel-management-app-3f47e',
    storageBucket: 'hotel-management-app-3f47e.appspot.com',
    iosClientId: '305904223967-tkn0pis15p0m0km590epa2i0qldlkb2s.apps.googleusercontent.com',
    iosBundleId: 'com.showoff.hotelManagementApp.RunnerTests',
  );
}
